repos:
  - repo: local
    hooks:
      - id: readability-check
        name: Readability Check for Markdown
        entry: python3 check_readability.py
        language: system
        pass_filenames: false
        files: \.md$
